window:
  width: 1280
  height: 720
  title: "机器人运动学调试界面"

robot:
  urdf_path: "/home/yuxia/Workspace/SingoriX/OmniLink/singorix_omnilink/config/galbot_description/galbot_one_golf_description/galbot_one_golf.urdf"

camera:
  distance: 3.0
  yaw: 0.0
  pitch: 0.0
  target: [0.0, 0.0, 0.0]

  rotate_speed: 0.005
  zoom_scale: 0.1
  dolly_scale: 0.02
  pan_scale: 0.0015
  min_distance: 0.2
  max_distance: 20.0

ui:
  fix_base_like_mujoco: false
  cjk_font_path: ""
  cjk_font_size: 18.0
  theme_preset: "moonlight" # current_dark | moonlight | spectrum_light

ros:
  enable: false

initial_pose:
  enable: true
  auto_apply_on_start: false
  head_joint_names: ["head_joint1", "head_joint2"]
  leg_joint_names: ["leg_joint1", "leg_joint2", "leg_joint3", "leg_joint4", "leg_joint5"]
  left_arm_joint_names:
    ["left_arm_joint1", "left_arm_joint2", "left_arm_joint3", "left_arm_joint4", "left_arm_joint5", "left_arm_joint6", "left_arm_joint7"]
  right_arm_joint_names:
    [
      "right_arm_joint1",
      "right_arm_joint2",
      "right_arm_joint3",
      "right_arm_joint4",
      "right_arm_joint5",
      "right_arm_joint6",
      "right_arm_joint7",
    ]
  head: [0.0, 0.00989756]
  leg: [0.499191, 1.49907, 1.00046, 0.0, -0.000431432]
  left_arm: [1.99995, -1.60004, -0.599905, -1.69994, 0.0, -0.799924, 0.0]
  right_arm: [-2.0, 1.60008, 0.600051, 1.70001, 0.0, 0.799993, 0.0]

ik:
  mode: "full_body" # single_chain | full_body
  full_body_backend: "wbc_chain_ik" # flex_ik | wbc_chain_ik
  full_body_iterations: 6
  chains:
    - label: "右臂"
      base_link: "torso_base_link"
      tip_link: "right_arm_end_effector_mount_link"
      base_link_candidates: ["torso_base_link", "torso_link", "pelvis"]
      tip_link_candidates: ["right_arm_end_effector_mount_link", "right_rubber_hand", "right_wrist_yaw_link"]
    - label: "左臂"
      base_link: "torso_base_link"
      tip_link: "left_arm_end_effector_mount_link"
      base_link_candidates: ["torso_base_link", "torso_link", "pelvis"]
      tip_link_candidates: ["left_arm_end_effector_mount_link", "left_rubber_hand", "left_wrist_yaw_link"]
